### ISSUE TITLE
Some errors occured in training

### ISSUE THREAD

**Issue by zzpDapeng** [mobvoi/wenet#35]
I followed the Tutorial of aishell, errors occured in  `bash run.sh --stage 4 --stop-stage 5` step

```
run.sh: init method is file:///home/dapeng/PycharmProjects/wenet/examples/aishell/s0/exp/sp_spec_aug/ddp_init
  File "wenet/bin/train.py", line 81
    collate_func = CollateFunc(**configs['collate_conf'],
                                                        ^
SyntaxError: invalid syntax
do model average and final checkpoint is exp/sp_spec_aug/avg_10.pt
Traceback (most recent call last):
  File "wenet/bin/average_model.py", line 7, in <module>
    import yaml
ImportError: No module named yaml
  File "wenet/bin/recognize.py", line 87
    test_collate_func = CollateFunc(**test_collate_conf, cmvn=args.cmvn)
                                                       ^
SyntaxError: invalid syntax
  File "wenet/bin/recognize.py", line 87
    test_collate_func = CollateFunc(**test_collate_conf, cmvn=args.cmvn)
                                                       ^
SyntaxError: invalid syntax
  File "  File "wenet/bin/recognize.pywenet/bin/recognize.py", line ", line 8787

        test_collate_func = CollateFunc(**test_collate_conf, cmvn=args.cmvn)
test_collate_func = CollateFunc(**test_collate_conf, cmvn=args.cmvn)
                                                                                                              ^
^
SyntaxErrorSyntaxError: : invalid syntaxinvalid syntax

Traceback (most recent call last):
  File "tools/compute-wer.py", line 365, in <module>
    with codecs.open(hyp_file, 'r', 'utf-8') as fh:
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/test_ctc_prefix_beam_search/text'
Traceback (most recent call last):
  File "tools/compute-wer.py", line 365, in <module>
    with codecs.open(hyp_file, 'r', 'utf-8') as fh:
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/test_attention_rescoring/text'
Traceback (most recent call last):
  File "tools/compute-wer.py", line 365, in <module>
Traceback (most recent call last):
    with codecs.open(hyp_file, 'r', 'utf-8') as fh:
  File "tools/compute-wer.py", line 365, in <module>
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    with codecs.open(hyp_file, 'r', 'utf-8') as fh:
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/test_ctc_greedy_search/text'
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/test_attention/text'

```

**Comment by zzpDapeng** [comment]
I created a python3 environment named wenet, and I change `source $ANACONDA_ROOT/bin/activate py3` in `path.sh` to `source $ANACONDA_ROOT/bin/activate wenet`.
I have installed pyyaml in my environment, but it still occurred `ImportError: No module named yaml` and I found py2.7 in the error message. It seems that my environment had not sourced correctly.

**Comment by whiteshirt0429** [comment]
the first issue is a bug that we have fixed, and you can pull main branch code again.
the second one, may be you can check whether path $ANACONDA_ROOT/bin has "activate".If you use a python3 environment named wenet, maybe you can try "conda activate wenet"  to run your environment.

**Comment by zzpDapeng** [comment]
> the first issue is a bug that we have fixed, and you can pull main branch code again.
> the second one, may be you can check whether path $ANACONDA_ROOT/bin has "activate".If you use a python3 environment named wenet, maybe you can try "conda activate wenet" to run your environment.

I have noticed #33 and pull the latest main branch code, but the error still appears：
```
run.sh: init method is file:///home/dapeng/PycharmProjects/wenet/examples/aishell/s0/exp/sp_spec_aug/ddp_init
  File "wenet/bin/train.py", line 81
    collate_func = CollateFunc(**configs['collate_conf'],
                                                                                    ^
SyntaxError: invalid syntax

```
This bug is different from #33 , which is:
```
 KeyError: 'spec_aug_conf'
```

**Comment by whiteshirt0429** [comment]
perhaps it was caused by your environments. You can make sure your running python version, we use python3, while your error maybe caused by wrong python version 2

**Comment by l2009312042** [comment]
if you use kaldi  ,you should comment the following line   in  file    kaldi/tools/env.sh ,which change your python to python2.7
#export PATH=/root/data/tools/kaldi/tools/python:${PATH}
export PATH=$PATH:/root/data/tools/kaldi/tools/kaldi_lm
export IRSTLM=/root/data/tools/kaldi/tools/irstlm
export PATH=${PATH}:${IRSTLM}/bin
#export PATH=/root/data/tools/kaldi/tools/python:${PATH}
export LIBLBFGS=/root/data/tools/kaldi/tools/liblbfgs-1.10
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:${LIBLBFGS}/lib/.libs

**Comment by zzpDapeng** [comment]
> if you use kaldi ,you should comment the following line in file kaldi/tools/env.sh ,which change your python to python2.7
> #export PATH=/root/data/tools/kaldi/tools/python:${PATH}
> export PATH=$PATH:/root/data/tools/kaldi/tools/kaldi_lm
> export IRSTLM=/root/data/tools/kaldi/tools/irstlm
> export PATH=${PATH}:${IRSTLM}/bin
> #export PATH=/root/data/tools/kaldi/tools/python:${PATH}
> export LIBLBFGS=/root/data/tools/kaldi/tools/liblbfgs-1.10
> export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:${LIBLBFGS}/lib/.libs

Thank you for your reply! It works.

**Comment by xzwworkplace** [comment]
> 

Thank you!!!!!!!!!!!!!!!!!!!
